   version: "3.9"
   services:
     auth:
       build: auth_service
       ports:
         - "8001:8000"
       env_file:
         - auth_service/.env

     post:
       build: post_service
       ports:
         - "8002:8000"
       env_file:
         - post_service/.env

     subscription:
       build: ./subscription
       ports:
         - "8003:8000"
       env_file:
         - ./subscription/.env

     db:
       image: postgres:15
       environment:
         POSTGRES_USER: admin
         POSTGRES_PASSWORD: admin
       ports:
         - "5432:5432"